version: '3.8'

services:
  app:
    image: node:18
    ports:
      - 3000:3000
      - 8002:8002 # remix dev websocket for live reload
    working_dir: /app
    command: sh -c "yarn && yarn dev"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      PAYLOAD_SECRET: secret123
      MONGODB_URI: mongodb://db:27017/mw
      PAYLOAD_PUBLIC_SERVER_URL: http://localhost:3000
      SMTP_HOST: mail
      SMTP_PORT: 1025
    depends_on:
      - db
  
  db:
    image: mongo:latest
    expose:
      - 27017
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
      - ./dump:/dump
        
  mail:
    image: maildev/maildev
    environment:
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
    ports:
      - 9001:1080
    expose:
      - 1025
  
volumes:
  data: