version: '3.8'

services:
  app:
    image: node:18-alpine
    ports:
      - 3000:3000
      - 8002:8002 # remix dev websocket for live reload
    working_dir: /app
    command: sh -c "yarn && yarn dev"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      PAYLOAD_SECRET: secret123
      MONGODB_URI: mongodb://db:27017/app
  
  db:
    image: mongo:latest
    ports:
      - 27017:27017
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
      - ./dump:/dump
  
volumes:
  data:
